#ifndef BLUE_MAX_DEFS_H
#define BLUE_MAX_DEFS_H

#include "SDL.h"

typedef struct {
    SDL_Renderer *renderer;
    SDL_Window *window;
} App;

#define ROTATION_SIN 0.68199836
#define ROTATION_COS 0.7313537
#define HEIGHT_Y_OFFSET (-0.7)

#define PLANE_BODY_LENGTH 80.0
#define PLANE_BODY_WIDTH 20.0
#define PLANE_BODY_HEIGHT 30.0
#define PLANE_WINGS_LENGTH 10.0
#define PLANE_WINGS_HEIGHT 20.0
#define PLANE_WINGS_WIDTH 80.0
#define PLANE_UP_SPEED 6.0
#define PLANE_DOWN_SPEED 3.0
#define PLANE_RELOAD_TIME_MS 1300
#define PLANE_SHOOT_CHANCE 0.2
#define PLANE_TEXTURE_CHANGE_INTERVAL_MS 80
#define PLANE_TEXTURE_WIDTH 80
#define PLANE_TEXTURE_HEIGHT (PLANE_TEXTURE_WIDTH * (57.0 / 94.0))

#define MAX_PLANES 4
#define MAX_PROJECTILES 128
#define MAX_BUILDINGS 4
#define MAX_TREES 256

#define PLAYER_FORWARD_SPEED 3.0
#define PLAYER_HORIZONTAL_SPEED 4.5
#define PLAYER_VERTICAL_SPEED 4.5
#define PLAYER_HORIZONTAL_BOUND 300.0
#define PLAYER_UP_BOUND 300.0
#define PLAYER_TEXTURE_CHANGE_INTERVAL_MS 80
#define PLAYER_TEXTURE_FORWARD_WIDTH 85
#define PLAYER_TEXTURE_FORWARD_HEIGHT (PLAYER_TEXTURE_FORWARD_WIDTH * (57.0 / 94.0))
#define PLAYER_TEXTURE_RIGHT_WIDTH (PLAYER_TEXTURE_FORWARD_WIDTH * (82.0 / 94.0))
#define PLAYER_TEXTURE_RIGHT_HEIGHT (PLAYER_TEXTURE_RIGHT_WIDTH * (56.0 / 82.0))
#define PLAYER_TEXTURE_LEFT_WIDTH (PLAYER_TEXTURE_FORWARD_WIDTH * (93.0 / 94.0))
#define PLAYER_TEXTURE_LEFT_HEIGHT (PLAYER_TEXTURE_FORWARD_WIDTH * (44.0 / 93.0))

#define PROJECTILE_SPEED_PLAYER 15.5
#define PROJECTILE_SPEED_UP 10.0
#define PROJECTILE_SPEED_DOWN 7.0
#define PROJECTILE_LENGTH 30.0
#define PROJECTILE_DIAMETER 5.0
#define PROJECTILE_TEXTURE_WIDTH 10
#define PROJECTILE_TEXTURE_HEIGHT (PROJECTILE_TEXTURE_WIDTH * (410.0 / 848.0))

#define BUILDING_TEXTURE_WIDTH 200
#define BUILDING_TEXTURE_HEIGHT (BUILDING_TEXTURE_WIDTH * (410.0 / 848.0))

#define SPAWN_DISTANCE_TO_CENTER 600.0
#define SPAWN_PLANE_CHANCE 0.005
#define SPAWN_PLANE_MIN_HEIGHT 100.0
#define SPAWN_BUILDING_CHANCE 0.002
#define SPAWN_BUILDING_MIN_DISTANCE 400.0

#define UNLOAD_DISTANCE_TO_CENTER 1000.0

#define COLOR_GRASS_R 37
#define COLOR_GRASS_G 114
#define COLOR_GRASS_B 0

#define TREE_WIDTH 80.0
#define TREE_HEIGHT 50.0
#define TREE_DEFAULT_DISTANCE 200.0
#define TREE_MAX_OFFSET 70.0
#define TREE_GRID_COLUMNS 8
#define TREE_GRID_ROWS 12
#define TREE_COLOR_R 37
#define TREE_COLOR_G 66
#define TREE_COLOR_B 0
#define TREE_ROOT_COLOR_R 0
#define TREE_ROOT_COLOR_G 0
#define TREE_ROOT_COLOR_B 0
#define TREE_BLACK_SQUARE_PROBABILITY 0.1

#endif //BLUE_MAX_DEFS_H
